/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoia;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.DefaultListModel;

/**
 *
 * @author jmoll
 */
public class SearchWindow extends javax.swing.JFrame {

    /**
     * Creates new form SearchWindow
     */
    public SearchWindow() {
        initComponents();
        yes = new ArrayList();
    }
    public SearchWindow(Naive naive){
        this();
        modelo = naive;
        start = true;
    }
    
    private Naive modelo;
    private List<Pelicula> resultados;
    private List<Integer> yes;
    private boolean start;
    
    private void ActualizarModelo(){
        List<Pelicula> copia = new ArrayList();
        resultados.forEach(r -> copia.add(r.copy()));
        List<Pelicula> si = new ArrayList();
        List<Pelicula> no = new ArrayList();
        for(int i = 0; i < copia.size(); i++){
            Pelicula p = copia.get(i);
            if(!modelo.inYesInput(p)){
                if(yes.contains(i)){
                    p.setValorizacion(Pelicula.YES);
                    si.add(p);
                }else{
                    p.calcValorazacion(Pelicula.NO);
                    no.add(p);
                }
            }
        }
        if(si.size()<no.size()){
            Random rand = new Random();
            while(no.size()>si.size()){
                no.remove(rand.nextInt(no.size()));
            }
        }
        for(Pelicula p : si) modelo.addMuestra(p);
        for(Pelicula p : no) modelo.addMuestra(p);
        yes.clear();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCBcampo = new javax.swing.JComboBox<>();
        jTFvalor = new javax.swing.JTextField();
        jBbuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlResult = new javax.swing.JList<>();
        jBabrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 800));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                alCerrar(evt);
            }
        });

        jCBcampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "genres", "plot_keywords", "actors", "color", "language", "country", "content_rating", "decade", "score", "director" }));

        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jlResult);

        jBabrir.setText("Abrir");
        jBabrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBabrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCBcampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFvalor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBabrir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBbuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBcampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBbuscar)
                    .addComponent(jBabrir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        // TODO add your handling code here:
        if(!start) ActualizarModelo();
        String campo = jCBcampo.getSelectedItem().toString();
        String valor = jTFvalor.getText();
        resultados = modelo.buscar(campo, valor);
        DefaultListModel listModel = new DefaultListModel();
        resultados.forEach((s) -> {
            listModel.addElement(s.getMovie_title());
        });
        jlResult.setModel(listModel);
        start = false;
    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jBabrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBabrirActionPerformed
        // TODO add your handling code here:
        if(!start){
            int index = jlResult.getSelectedIndex();
            yes.add(index);
            new VerPelicula(resultados.get(index)).setVisible(true);
        }
    }//GEN-LAST:event_jBabrirActionPerformed

    private void alCerrar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_alCerrar
        // TODO add your handling code here:
        if(!start) ActualizarModelo();
    }//GEN-LAST:event_alCerrar

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SearchWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBabrir;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JComboBox<String> jCBcampo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFvalor;
    private javax.swing.JList<String> jlResult;
    // End of variables declaration//GEN-END:variables
}
